//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarkets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supermarket
    {
        public Supermarket()
        {
            this.Supermarket_Sales = new HashSet<Supermarket_Sales>();
            this.SupermarketProducts = new HashSet<SupermarketProduct>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Supermarket_Sales> Supermarket_Sales { get; set; }
        public virtual ICollection<SupermarketProduct> SupermarketProducts { get; set; }
    }
}
